"""Add address to appointments and recommended_by to prospects

Revision ID: 0aee3ae8cf24
Revises: 
Create Date: 2025-07-16 22:16:09.331976

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0aee3ae8cf24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=256), nullable=True))

    with op.batch_alter_table('prospects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recommended_by_id', sa.Integer(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=32),
               existing_nullable=False)
        batch_op.alter_column('observation',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('PENDING', 'NO_RESPONSE', 'REJECTED', 'SOLD', 'FOLLOW_UP', 'BLACKLISTED', 'SCHEDULED', 'scheduled', name='prospectstatus'),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('prospects_created_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'prospects', ['recommended_by_id'], ['id'])
        batch_op.drop_column('created_by')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('prospects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('prospects_created_by_fkey'), 'users', ['created_by'], ['id'])
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('PENDING', 'NO_RESPONSE', 'REJECTED', 'SOLD', 'FOLLOW_UP', 'BLACKLISTED', 'SCHEDULED', 'scheduled', name='prospectstatus'),
               nullable=True)
        batch_op.alter_column('observation',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('recommended_by_id')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
